### ISSUE TITLE
预览本地滑动闪退

### ISSUE THREAD

**Issue by DongDian455** [lihangleo2/mPro#6]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.leo.myactivityoptions.localdemo.LocalMainActivity$2.onMapSharedElements(LocalMainActivity.java:94)
        at android.app.ActivityTransitionCoordinator.viewsReady(ActivityTransitionCoordinator.java:229)
        at android.app.EnterTransitionCoordinator.viewsReady(EnterTransitionCoordinator.java:132)
        at android.app.EnterTransitionCoordinator.lambda$-android_app_EnterTransitionCoordinator_6436(EnterTransitionCoordinator.java:164)
        at android.app.-$Lambda$CsyQO--8YdRe5wlajUCi-L98enA$3.$m$0(Unknown Source:8)
        at android.app.-$Lambda$CsyQO--8YdRe5wlajUCi-L98enA$3.run(Unknown Source:0)
        at com.android.internal.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:78)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2372)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1421)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6842)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by lihangleo2** [comment]
每次都会报错吗 还是偶尔一次?

**Comment by lihangleo2** [comment]
兄弟！如果看到的话。回复我

**Comment by DongDian455** [comment]
> 兄弟！如果看到的话。回复我

必现的，很明显的一个bug

**Comment by lihangleo2** [comment]
我这边的设备都不会触发这个bug、你帮我在LocalMainActivity这个类里。在这里对itemView做个非空判断试试
`
                        View itemView = gridLayoutManager.findViewByPosition(i);
                        ImageView imageView = itemView.findViewById(R.id.imageView);

                        //注意这里第二个参数，如果放置的是条目的item则动画不自然。放置对应的 
                        imageView则完美
                        sharedElements.put(mipmaps.get(i).getTag(), imageView);
                        bundle = null;
`

**Comment by lihangleo2** [comment]
我这边的设备都不会触发这个bug、你帮我在LocalMainActivity这个类里。在这里对itemView做个非空判断试试
`                        View itemView = gridLayoutManager.findViewByPosition(i);
                        ImageView imageView = itemView.findViewById(R.id.imageView);

                        //注意这里第二个参数，如果放置的是条目的item则动画不自然。放置对应的imageView则完美
                        sharedElements.put(mipmaps.get(i).getTag(), imageView);
                        bundle = null;`

**Comment by lihangleo2** [comment]
我这里的设备都不会触发这个bug。兄弟，你帮我在LocalMainActivity里的第94行，对itemView进行一个非空判断，不为空才走下面。试试，谢了

**Comment by DongDian455** [comment]
判空了肯定就不会报NPE了，但同时转场动画也没有了，出现这个问题应该是你
```
@Subscribe(threadMode = ThreadMode.MAIN)
    public void onbackEvent(CanScrollBean canScrollBean) {//这里用于列表元素共享的时候，列表下滑
        recyclerView.scrollToPosition(canScrollBean.getPosition());
    }
```
这个方法的问题，虽然调用滑动位置，但是在返回的时候不一定已经滑到该位置并且更新了列表信息，所以你再findViewByPosition会为空

我的做法是这样
```
    postponeEnterTransition()
                            mRecyclerView.addOnLayoutChangeListener(object : View.OnLayoutChangeListener {
                                override fun onLayoutChange(v: View?, left: Int, top: Int, right: Int, bottom: Int, oldLeft: Int, oldTop: Int, oldRight: Int, oldBottom: Int) {
                                    mRecyclerView.removeOnLayoutChangeListener(this)
                                    startPostponedEnterTransition()
                                }
                            })
                            mRecyclerView.scrollToPosition(index)
```

**Comment by DongDian455** [comment]
方法调用的时机是在onActivityReenter的时候，这样可以不使用eventbus的同时也能做到转场

**Comment by lihangleo2** [comment]
嗯 非常感谢。调用时机我知道。我记得我当时用EventBus是因为，想把动画做到无感衔接。点击大图后，左右滑动我就直接通知recyclerView去滑动，意思不返回，我就已经把对应位置滑动了。如果用onActivityReenter，是要在返回才触发。但是这个bug不知道为什么会出现！！位置不应该找不到的、、
